from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess  # nosec B404 - this test invokes a fixed local checker command.
import sys


ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "scripts" / "check_rch_dependency_convergence.py"


def _load_checker_module():
    spec = importlib.util.spec_from_file_location("check_rch_dependency_convergence", SCRIPT)
    if spec is None or spec.loader is None:
        raise AssertionError("failed to load check_rch_dependency_convergence module")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _expect(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def _expect_equal(left: object, right: object) -> None:
    if left != right:
        raise AssertionError(f"{left!r} != {right!r}")


def _write_lock(root: Path, packages: list[tuple[str, str]]) -> None:
    lines = ["# This file is automatically @generated by Cargo.\n"]
    for name, version in packages:
        lines.extend(
            [
                "[[package]]\n",
                f'name = "{name}"\n',
                f'version = "{version}"\n',
                "\n",
            ]
        )
    (root / "Cargo.lock").write_text("".join(lines), encoding="utf-8")


def _write_manifest(path: Path, package: str, dependency_requirement: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "[package]",
                f'name = "{package}"',
                'version = "0.1.0"',
                "",
                "[dependencies]",
                f'getrandom = "{dependency_requirement}"',
                "",
            ]
        ),
        encoding="utf-8",
    )


def _run_checker(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )  # nosec B603 - test invokes this repository's checker with fixed argv.


def test_requirement_parser_matches_cargo_caret_lane() -> None:
    checker = _load_checker_module()

    _expect(checker.is_candidate_convergence_conflict("0.4.2", "^0.4.3"), "0.4.2 should fail ^0.4.3")
    _expect(
        not checker.is_candidate_convergence_conflict("0.4.3", "^0.4.3"),
        "0.4.3 should satisfy ^0.4.3",
    )
    _expect(
        not checker.is_candidate_convergence_conflict("0.5.0", "^0.4.3"),
        "0.5.0 should be treated as a different compatibility lane",
    )
    _expect(checker.is_candidate_convergence_conflict("1.2.9", "1.3.0"), "1.2.9 should fail 1.3.0")


def test_json_fails_on_getrandom_same_lane_mismatch(tmp_path: Path) -> None:
    frankentui = tmp_path / "frankentui"
    frankensqlite = tmp_path / "frankensqlite"
    frankentui.mkdir()
    frankensqlite.mkdir()
    _write_lock(frankentui, [("getrandom", "0.4.2")])
    _write_manifest(
        frankensqlite / "crates" / "fsqlite-ext-misc" / "Cargo.toml",
        "fsqlite-ext-misc",
        "^0.4.3",
    )

    proc = _run_checker(
        "--root",
        f"frankentui={frankentui}",
        "--root",
        f"frankensqlite={frankensqlite}",
        "--package",
        "getrandom",
        "--json",
    )

    _expect_equal(proc.returncode, 21)
    report = json.loads(proc.stdout)
    _expect_equal(report["verdict"], "FAIL")
    _expect_equal(report["summary"]["mismatch_count"], 1)
    mismatch = report["mismatches"][0]
    _expect_equal(mismatch["package"], "getrandom")
    _expect_equal(mismatch["selected_version"], "0.4.2")
    _expect_equal(mismatch["selected_root"], "frankentui")
    _expect_equal(mismatch["requirement"], "^0.4.3")
    _expect_equal(mismatch["dependency_owner"], "fsqlite-ext-misc")
    _expect_equal(mismatch["manifest_root"], "frankensqlite")
    _expect(
        mismatch["manifest_path"].endswith("crates/fsqlite-ext-misc/Cargo.toml"),
        "manifest path should name fsqlite-ext-misc Cargo.toml",
    )


def test_json_passes_when_locked_version_satisfies_requirement(tmp_path: Path) -> None:
    frankentui = tmp_path / "frankentui"
    frankensqlite = tmp_path / "frankensqlite"
    frankentui.mkdir()
    frankensqlite.mkdir()
    _write_lock(frankentui, [("getrandom", "0.4.3")])
    _write_manifest(
        frankensqlite / "crates" / "fsqlite-ext-misc" / "Cargo.toml",
        "fsqlite-ext-misc",
        "^0.4.3",
    )

    proc = _run_checker(
        "--root",
        f"frankentui={frankentui}",
        "--root",
        f"frankensqlite={frankensqlite}",
        "--json",
    )

    _expect_equal(proc.returncode, 0)
    report = json.loads(proc.stdout)
    _expect_equal(report["verdict"], "PASS")
    _expect_equal(report["mismatches"], [])
    _expect_equal(report["summary"]["mismatch_count"], 0)


def test_human_output_names_owner_manifest_and_selected_lock(tmp_path: Path) -> None:
    frankentui = tmp_path / "frankentui"
    frankensqlite = tmp_path / "frankensqlite"
    frankentui.mkdir()
    frankensqlite.mkdir()
    _write_lock(frankentui, [("getrandom", "0.4.2")])
    _write_manifest(
        frankensqlite / "crates" / "fsqlite-ext-misc" / "Cargo.toml",
        "fsqlite-ext-misc",
        "^0.4.3",
    )

    proc = _run_checker(
        "--root",
        f"frankentui={frankentui}",
        "--root",
        f"frankensqlite={frankensqlite}",
    )

    _expect_equal(proc.returncode, 21)
    _expect("rch dependency convergence preflight: FAIL" in proc.stdout, "human output should fail")
    _expect("getrandom selected 0.4.2" in proc.stdout, "human output should name selected version")
    _expect("fsqlite-ext-misc" in proc.stdout, "human output should name dependency owner")
    _expect("Cargo.lock" in proc.stdout, "human output should name selected lockfile")


def test_renamed_dependency_uses_package_name(tmp_path: Path) -> None:
    checker = _load_checker_module()
    root = checker.RootSpec("example", tmp_path)
    crate = tmp_path / "crates" / "renamed" / "Cargo.toml"
    crate.parent.mkdir(parents=True)
    crate.write_text(
        "\n".join(
            [
                "[package]",
                'name = "renamed"',
                'version = "0.1.0"',
                "",
                "[dependencies]",
                'rng = { package = "getrandom", version = "^0.4.3" }',
                "",
            ]
        ),
        encoding="utf-8",
    )

    requirements = checker.parse_manifest_requirements(root, checker.DEFAULT_MANIFEST_GLOBS)

    _expect_equal(len(requirements), 1)
    _expect_equal(requirements[0].dependency_key, "rng")
    _expect_equal(requirements[0].package, "getrandom")
