//! Cross-crate differential tests between `frankenengine-node` and `frankenengine-verifier-sdk`.
//!
//! Validates that data structures generated by the runtime product crate
//! (such as extension registry manifests and counterfactual replay bundles)
//! are independently verified by the verifier SDK without divergence.

use std::collections::BTreeMap;

use ed25519_dalek::{Signer, SigningKey};
use frankenengine_node::supply_chain::artifact_signing::{self, KeyId, KeyRing};
use frankenengine_node::supply_chain::extension_registry::{
    AdmissionKernel, ExtensionSignature, RegistrationRequest, RegistryConfig, SignedExtension,
    SignedExtensionRegistry, VersionEntry, canonical_registration_manifest_bytes,
};
use frankenengine_node::supply_chain::provenance::{
    self, AttestationEnvelopeFormat, AttestationLink, ChainLinkRole, ProvenanceAttestation,
    VerificationPolicy,
};
use frankenengine_node::supply_chain::transparency_verifier::TransparencyPolicy;
use frankenengine_node::tools::counterfactual_replay::{
    CounterfactualReplayEngine, PolicyConfig, to_canonical_json,
};
use frankenengine_node::tools::replay_bundle::{
    EventType, RawEvent, ReplayBundle, generate_replay_bundle,
};
use frankenengine_verifier_sdk::bundle::{BundleError, verify_ed25519_signature};
use frankenengine_verifier_sdk::counterfactual::{
    CounterfactualReceiptError, verify_counterfactual_receipt,
};

type TestResult<T = ()> = Result<T, Box<dyn std::error::Error>>;

struct PublishedRegistryEntry {
    entry: SignedExtension,
    manifest_bytes: Vec<u8>,
    public_key: ed25519_dalek::VerifyingKey,
}

#[test]
fn sdk_verifies_franken_node_registry_signature_differential() -> TestResult {
    let published = publish_signed_registry_entry()?;
    let key_id = KeyId::from_verifying_key(&published.public_key);

    assert_eq!(published.entry.signature.algorithm, "ed25519");
    assert_eq!(published.entry.signature.key_id, key_id.to_string());

    verify_ed25519_signature(
        &published.public_key,
        &published.manifest_bytes,
        &published.entry.signature.signature_bytes,
    )?;

    let mut mutated_manifest = published.manifest_bytes.clone();
    if let Some(first_byte) = mutated_manifest.first_mut() {
        *first_byte ^= 0x01;
    }

    let Err(error) = verify_ed25519_signature(
        &published.public_key,
        &mutated_manifest,
        &published.entry.signature.signature_bytes,
    ) else {
        return Err("mutated registry manifest unexpectedly verified".into());
    };
    assert_eq!(error, BundleError::Ed25519SignatureInvalid);

    Ok(())
}

fn publish_signed_registry_entry() -> TestResult<PublishedRegistryEntry> {
    let now_epoch = 1_700_000_400;
    let signing_key = SigningKey::from_bytes(&[42_u8; 32]);
    let verifying_key = signing_key.verifying_key();
    let mut registry = registry_with_publisher_key(verifying_key);
    let request = registration_request(&signing_key, now_epoch)?;
    let manifest_bytes = request.manifest_bytes.clone();
    let registered_key_id = request.signature.key_id.clone();

    let result = registry.register(request, "trace-sdk-independent-registry-verify", now_epoch);
    if !result.success {
        return Err(format!("registry admission failed: {}", result.detail).into());
    }
    let extension_id = result
        .extension_id
        .ok_or("registry admission succeeded without extension id")?;
    let entry = registry
        .query(&extension_id)
        .ok_or("registered extension missing from registry")?
        .clone();
    let public_key = registry
        .admission_kernel()
        .key_ring
        .get_key(&KeyId(registered_key_id))
        .copied()
        .ok_or("registered publisher key missing from key ring")?;

    Ok(PublishedRegistryEntry {
        entry,
        manifest_bytes,
        public_key,
    })
}

fn registry_with_publisher_key(
    verifying_key: ed25519_dalek::VerifyingKey,
) -> SignedExtensionRegistry {
    let mut key_ring = KeyRing::new();
    key_ring.add_key(verifying_key);
    let mut provenance_policy = VerificationPolicy::development_profile();
    provenance_policy.add_trusted_signer_key("pub-001", &verifying_key);
    SignedExtensionRegistry::new(
        RegistryConfig::default(),
        AdmissionKernel {
            key_ring,
            provenance_policy,
            transparency_policy: TransparencyPolicy {
                required: false,
                pinned_roots: Vec::new(),
            },
        },
    )
}

fn registration_request(
    signing_key: &SigningKey,
    now_epoch: u64,
) -> TestResult<RegistrationRequest> {
    let initial_version = VersionEntry {
        version: "1.0.0".to_string(),
        parent_version: None,
        content_hash: "c".repeat(64),
        registered_at: "2023-11-14T22:13:20Z".to_string(),
        compatible_with: vec!["franken-node".to_string()],
    };
    let tags = vec!["sdk-verifier".to_string(), "registry".to_string()];
    let manifest_bytes = canonical_registration_manifest_bytes(
        "chain-verify-registry",
        "pub-001",
        &initial_version,
        &tags,
    )?;
    let signature_bytes = artifact_signing::sign_bytes(signing_key, &manifest_bytes);
    let key_id = KeyId::from_verifying_key(&signing_key.verifying_key());

    Ok(RegistrationRequest {
        name: "chain-verify-registry".to_string(),
        description: "SDK verifier independent registry signature fixture".to_string(),
        publisher_id: "pub-001".to_string(),
        signature: ExtensionSignature {
            key_id: key_id.to_string(),
            algorithm: "ed25519".to_string(),
            signature_bytes,
            signed_at: "2023-11-14T22:13:20Z".to_string(),
        },
        provenance: provenance_attestation(signing_key, now_epoch)?,
        initial_version,
        tags,
        manifest_bytes,
        transparency_proof: None,
    })
}

fn provenance_signing_keys(signing_key: &SigningKey) -> BTreeMap<String, SigningKey> {
    BTreeMap::from([(
        "pub-001".to_string(),
        SigningKey::from_bytes(&signing_key.to_bytes()),
    )])
}

fn provenance_attestation(
    signing_key: &SigningKey,
    now_epoch: u64,
) -> TestResult<ProvenanceAttestation> {
    let mut attestation = ProvenanceAttestation {
        schema_version: "1.0".to_string(),
        source_repository_url: "https://example.invalid/franken-node/extensions.git".to_string(),
        build_system_identifier: "franken-node-registry-fixture".to_string(),
        builder_identity: "pub-001".to_string(),
        builder_version: "1.0.0".to_string(),
        vcs_commit_sha: "abc123def4567890abc123def4567890abc123def".to_string(),
        build_timestamp_epoch: now_epoch.saturating_sub(60),
        reproducibility_hash: "d".repeat(64),
        input_hash: "e".repeat(64),
        output_hash: "f".repeat(64),
        slsa_level_claim: 2,
        envelope_format: AttestationEnvelopeFormat::FrankenNodeEnvelopeV1,
        links: vec![AttestationLink {
            role: ChainLinkRole::Publisher,
            signer_id: "pub-001".to_string(),
            signer_version: "1.0.0".to_string(),
            signature: String::new(),
            signed_payload_hash: "f".repeat(64),
            issued_at_epoch: now_epoch.saturating_sub(60),
            expires_at_epoch: now_epoch.saturating_add(86_400),
            revoked: false,
        }],
        custom_claims: Default::default(),
    };
    provenance::sign_links_in_place(&mut attestation, &provenance_signing_keys(signing_key))?;
    Ok(attestation)
}

#[test]
fn sdk_counterfactual_receipt_roundtrip_and_tamper_detection_differential() -> TestResult {
    let baseline_bundle = fixture_bundle()?;
    let engine = CounterfactualReplayEngine::default();
    let baseline_policy = PolicyConfig::from_bundle(&baseline_bundle);
    let alternate_policy = PolicyConfig {
        policy_name: "strict".to_string(),
        quarantine_threshold: 70,
        observe_threshold: 45,
        degraded_mode_bias: 20,
    };
    let output =
        engine.replay_with_baseline(&baseline_bundle, &baseline_policy, &alternate_policy)?;
    let signing_key = SigningKey::from_bytes(&[17_u8; 32]);
    let canonical_output = to_canonical_json(&output)?;
    let signature = signing_key.sign(canonical_output.as_bytes());
    let signature_bytes = signature.to_bytes();

    verify_counterfactual_receipt(
        &baseline_bundle,
        &output,
        &signing_key.verifying_key(),
        &signature_bytes,
    )?;

    let mut tampered_output = output.clone();
    tampered_output.summary_statistics.changed_decisions = tampered_output
        .summary_statistics
        .changed_decisions
        .saturating_add(1);

    let Err(error) = verify_counterfactual_receipt(
        &baseline_bundle,
        &tampered_output,
        &signing_key.verifying_key(),
        &signature_bytes,
    ) else {
        return Err("tampered counterfactual output unexpectedly verified".into());
    };
    if error != CounterfactualReceiptError::Signature(BundleError::Ed25519SignatureInvalid) {
        return Err(format!("unexpected tamper verification error: {error}").into());
    }

    Ok(())
}

fn fixture_bundle() -> TestResult<ReplayBundle> {
    let events = vec![
        RawEvent::new(
            "2026-02-20T12:00:00.000001Z",
            EventType::ExternalSignal,
            serde_json::json!({
                "detector": "counterfactual-verifier-fixture",
                "severity": "high",
                "signal": "extension-authority-escalation"
            }),
        )
        .with_state_snapshot(serde_json::json!({
            "epoch": 91_u64,
            "active_substrates": ["node", "bun", "asupersync"],
            "active_policies": ["extension-quarantine", "counterfactual-replay"]
        }))
        .with_policy_version("counterfactual-baseline-2026-04"),
        RawEvent::new(
            "2026-02-20T12:00:00.000250Z",
            EventType::PolicyEval,
            serde_json::json!({
                "confidence": 68_u64,
                "decision": "observe",
                "rule_id": "policy.counterfactual.recheck"
            }),
        )
        .with_causal_parent(1),
        RawEvent::new(
            "2026-02-20T12:00:00.000500Z",
            EventType::OperatorAction,
            serde_json::json!({
                "action": "continue-with-guardrail",
                "confidence": 46_u64,
                "degraded_mode": true,
                "result": "accepted"
            }),
        )
        .with_causal_parent(2),
    ];

    Ok(generate_replay_bundle("INC-SDK-CF-VERIFY-001", &events)?)
}
