//! Property harness for the API `traceparent` request-header decoder.
//!
//! The parser sits on an untrusted HTTP header boundary, so arbitrary inputs
//! must never panic or allocate attacker-controlled output. Accepted contexts
//! are constrained to the fixed W3C field widths.

use frankenengine_node::api::middleware::TraceContext;
use proptest::prelude::*;
use std::panic::{AssertUnwindSafe, catch_unwind};

const MAX_HEADER_BYTES: usize = 4096;
const VALID_TRACEPARENT_BYTES: usize = 55;
const TRACE_ID_BYTES: usize = 32;
const SPAN_ID_BYTES: usize = 16;

fn parse_no_panic(header: &str) -> Option<TraceContext> {
    let parsed = catch_unwind(AssertUnwindSafe(|| TraceContext::from_traceparent(header)));
    assert!(
        parsed.is_ok(),
        "traceparent parser panicked for {} input bytes",
        header.len()
    );
    parsed.expect("panic checked")
}

fn assert_bounded_context(context: TraceContext) {
    assert_eq!(context.trace_id.len(), TRACE_ID_BYTES);
    assert!(context.trace_id.chars().all(|c| c.is_ascii_hexdigit()));
    assert!(context.trace_id.chars().all(|c| !c.is_ascii_uppercase()));

    assert_eq!(context.span_id.len(), SPAN_ID_BYTES);
    assert!(context.span_id.chars().all(|c| c.is_ascii_hexdigit()));
    assert!(context.span_id.chars().all(|c| !c.is_ascii_uppercase()));

    assert_eq!(context.to_traceparent().len(), VALID_TRACEPARENT_BYTES);
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 384,
        max_shrink_iters: 1024,
        .. ProptestConfig::default()
    })]

    #[test]
    fn arbitrary_traceparent_headers_do_not_panic_or_return_unbounded_context(
        bytes in proptest::collection::vec(0_u8..=127, 0..=MAX_HEADER_BYTES),
    ) {
        let header = String::from_utf8(bytes).expect("generated bytes are ASCII");
        let parsed = parse_no_panic(&header);

        if header.len() != VALID_TRACEPARENT_BYTES {
            prop_assert!(parsed.is_none());
        }

        if let Some(context) = parsed {
            assert_bounded_context(context);
        }
    }
}

#[test]
fn adversarial_traceparent_corpus_rejects_without_panic() {
    let corpus = [
        "",
        "00",
        "00-",
        "ff-00000000000000000000000000000001-0000000000000001-01",
        "00-00000000000000000000000000000000-0000000000000001-01",
        "00-00000000000000000000000000000001-0000000000000000-01",
        "00-00000000000000000000000000000001-0000000000000001-010",
        "00-00000000000000000000000000000001-0000000000000001-01-extra",
        "00-0000000000000000000000000000000G-0000000000000001-01",
        "00-00000000000000000000000000000001-000000000000000G-01",
        "00-00000000000000000000000000000001-0000000000000001-GG",
        "00-00000000000000000000000000000001-0000000000000001-\0\0",
    ];

    for header in corpus {
        if let Some(context) = parse_no_panic(header) {
            assert_bounded_context(context);
        }
    }

    let long_dash_run = "-".repeat(MAX_HEADER_BYTES * 16);
    assert!(parse_no_panic(&long_dash_run).is_none());

    let long_hex_run = format!(
        "00-{}-{}-01",
        "a".repeat(MAX_HEADER_BYTES),
        "b".repeat(1024)
    );
    assert!(parse_no_panic(&long_hex_run).is_none());
}
