#!/usr/bin/env python3
"""Golden artifact test for workspace pressure policy decisions (bd-p9mpd.4)."""

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GOLDEN_DIR = ROOT / "tests" / "golden"
POLICY_GOLDEN_JSON = GOLDEN_DIR / "workspace_pressure_policy_decisions.json"
UPDATE_GOLDENS_ENV = "UPDATE_GOLDENS"
EXPECTED_SCHEMA_VERSION = "bd-p9mpd.4/v1"
EXPECTED_SCENARIOS = [
    "healthy",
    "disk_pressure",
    "build_pressure",
    "rch_unavailable",
    "coordination_degraded",
    "critical",
]
EXPECTED_WORK_CLASSES = [
    "SourceOnly",
    "DocsGate",
    "Validation",
    "Benchmark",
    "Fuzzing",
    "Cleanup",
]


def generate_policy_golden_artifacts():
    """Generate golden artifacts for workspace pressure policy decisions."""
    raise RuntimeError(
        "workspace pressure policy goldens are generated by the Rust integration "
        "test using the real policy implementation. Run "
        "UPDATE_GOLDENS=1 RCH_ENV_ALLOWLIST=CARGO_TARGET_DIR,UPDATE_GOLDENS "
        "rch exec -- env CARGO_TARGET_DIR=/tmp/rch_target_franken_node_pane_6 "
        "UPDATE_GOLDENS=1 cargo test -p frankenengine-node --test "
        "workspace_pressure_governance_e2e --no-default-features "
        "workspace_pressure_policy_decision_golden_matches_real_policy"
    )

def load_golden_artifact():
    """Load the checked-in golden artifact without mutating it."""
    if not POLICY_GOLDEN_JSON.exists():
        raise RuntimeError(
            f"Golden artifact missing: {POLICY_GOLDEN_JSON}. "
            f"Run the Rust integration target with {UPDATE_GOLDENS_ENV}=1 to create it."
        )
    try:
        data = json.loads(POLICY_GOLDEN_JSON.read_text())
    except json.JSONDecodeError as err:
        raise RuntimeError(f"Golden artifact is not valid JSON: {err}") from err
    if not isinstance(data, dict):
        raise RuntimeError("Golden artifact root must be a JSON object")
    return data


def canonical_json(data):
    """Return the canonical JSON byte representation used by the checked-in fixture."""
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def test_hygiene_detection_structure():
    """Test that hygiene detection produces expected structure."""
    print("Testing hygiene detection structure...")

    # Simulate target directory hygiene data structure
    target_hygiene = {
        "status": "clean",
        "artifact_count": 0,
        "stale_artifact_count": 0,
        "total_size_bytes": 0,
        "oldest_artifact_age_seconds": None,
        "newest_artifact_age_seconds": None,
        "diagnostic_details": ["Target directory does not exist - clean state"]
    }

    # Simulate sync root hygiene data structure
    sync_root_hygiene = {
        "status": "clean",
        "modified_file_count": 0,
        "untracked_file_count": 0,
        "conflicted_file_count": 0,
        "staged_change_count": 0,
        "commit_distance_ahead": None,
        "commit_distance_behind": None,
        "diagnostic_details": ["Working directory is clean"]
    }

    # Verify required fields exist
    required_target_fields = [
        "status", "artifact_count", "stale_artifact_count", "total_size_bytes",
        "oldest_artifact_age_seconds", "newest_artifact_age_seconds", "diagnostic_details"
    ]
    for field in required_target_fields:
        if field not in target_hygiene:
            print(f"Missing target hygiene field: {field}")
            return False

    required_sync_fields = [
        "status", "modified_file_count", "untracked_file_count", "conflicted_file_count",
        "staged_change_count", "commit_distance_ahead", "commit_distance_behind", "diagnostic_details"
    ]
    for field in required_sync_fields:
        if field not in sync_root_hygiene:
            print(f"Missing sync root hygiene field: {field}")
            return False

    print("✓ Hygiene detection structure is valid")
    return True

def test_golden_artifact_structure():
    """Test that the golden artifact has expected structure."""
    data = load_golden_artifact()

    # Verify structure
    required_fields = ["schema_version", "description", "scenarios", "decision_matrix"]
    for field in required_fields:
        if field not in data:
            print(f"Missing field: {field}")
            return False

    if data["schema_version"] != EXPECTED_SCHEMA_VERSION:
        print(f"Invalid schema_version: {data['schema_version']}")
        return False

    # Verify scenarios
    for scenario in EXPECTED_SCENARIOS:
        if scenario not in data["scenarios"]:
            print(f"Missing scenario: {scenario}")
            return False

        scenario_data = data["scenarios"][scenario]
        if "inputs" not in scenario_data or "work_decisions" not in scenario_data:
            print(f"Invalid scenario structure: {scenario}")
            return False
        for work_class in EXPECTED_WORK_CLASSES:
            if work_class not in scenario_data["work_decisions"]:
                print(f"Missing decision for {scenario}/{work_class}")
                return False

    # Verify decision matrix
    if not isinstance(data["decision_matrix"], list):
        print("Decision matrix should be a list")
        return False

    expected_matrix_len = len(EXPECTED_SCENARIOS) * len(EXPECTED_WORK_CLASSES)
    if len(data["decision_matrix"]) != expected_matrix_len:
        print(
            "Decision matrix length "
            f"{len(data['decision_matrix'])} != {expected_matrix_len}"
        )
        return False

    for entry in data["decision_matrix"]:
        for field in [
            "scenario",
            "work_class",
            "priority",
            "decision",
            "reason_code",
            "has_cleanup_candidates",
        ]:
            if field not in entry:
                print(f"Decision matrix entry missing {field}: {entry}")
                return False
        decisions = data["scenarios"][entry["scenario"]]["work_decisions"]
        decision = decisions[entry["work_class"]]
        if entry["decision"] != decision["admission"]:
            print(f"Decision matrix admission mismatch: {entry}")
            return False
        if entry["reason_code"] != decision["reason_code"]:
            print(f"Decision matrix reason_code mismatch: {entry}")
            return False
        if entry["has_cleanup_candidates"] != bool(decision["cleanup_candidates"]):
            print(f"Decision matrix cleanup flag mismatch: {entry}")
            return False

    raw = POLICY_GOLDEN_JSON.read_text()
    if raw != canonical_json(data):
        print(
            "Golden artifact is not canonical. "
            f"Run the Rust integration target with {UPDATE_GOLDENS_ENV}=1."
        )
        return False

    print(f"Golden artifact structure is valid ({len(data['decision_matrix'])} decisions)")
    return True


def main():
    """Verify the checked-in golden artifact without rewriting it."""
    print("Verifying workspace pressure policy golden artifact...")

    if os.environ.get(UPDATE_GOLDENS_ENV):
        try:
            generate_policy_golden_artifacts()
        except RuntimeError as err:
            print(err)
            return False

    if test_golden_artifact_structure():
        if test_hygiene_detection_structure():
            print("All tests passed")
            return True

    return False


if __name__ == "__main__":
    exit(0 if main() else 1)
